/**This class allows for a user to request hygiene products.
 * @author Daniel Grimm
 *
 * Code snippets have been used from code automatically generated by Amazon Web Services.*/

package nosql;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "supplydrop-mobilehub-503652753-HYGIENE_REQUEST")

public class HYGIENE_REQUEST {

    private Double _requestID;
    private Boolean _soap;
    private Boolean _toothbrush;
    private Boolean _toothpaste;

    @DynamoDBHashKey(attributeName = "requestID")
    @DynamoDBAttribute(attributeName = "requestID")
    public Double getRequestID() {
        return _requestID;
    }

    public void setRequestID(final Double _requestID) {
        this._requestID = _requestID;
    }
    @DynamoDBAttribute(attributeName = "soap")
    public Boolean getSoap() {
        return _soap;
    }

    public void setSoap(final Boolean _soap) {
        this._soap = _soap;
    }
    @DynamoDBAttribute(attributeName = "toothbrush")
    public Boolean getToothbrush() {
        return _toothbrush;
    }

    public void setToothbrush(final Boolean _toothbrush) {
        this._toothbrush = _toothbrush;
    }
    @DynamoDBAttribute(attributeName = "toothpaste")
    public Boolean getToothpaste() {
        return _toothpaste;
    }

    public void setToothpaste(final Boolean _toothpaste) {
        this._toothpaste = _toothpaste;
    }

}