/**This class allows for a user to make a generic request.
 * @author Daniel Grimm
 *
 * Code snippets have been used from code automatically generated by Amazon Web Services.*/

package nosql;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "supplydrop-mobilehub-503652753-REQUEST")

public class REQUEST {

    private Double _requestID;
    private Double _apparelRequestID;
    private Boolean _food;
    private Boolean _fulfilled;
    private Double _hygieneRequestID;
    private String _location;
    private String _notes;
    private Double _timestamp;
    private String _username;

    @DynamoDBHashKey(attributeName = "requestID")
    @DynamoDBAttribute(attributeName = "requestID")
    public Double getRequestID() {
        return _requestID;
    }

    public void setRequestID(final Double _requestID) {
        this._requestID = _requestID;
    }
    @DynamoDBAttribute(attributeName = "apparelRequestID")
    public Double getApparelRequestID() {
        return _apparelRequestID;
    }

    public void setApparelRequestID(final Double _apparelRequestID) {
        this._apparelRequestID = _apparelRequestID;
    }
    @DynamoDBAttribute(attributeName = "food")
    public Boolean getFood() {
        return _food;
    }

    public void setFood(final Boolean _food) {
        this._food = _food;
    }
    @DynamoDBAttribute(attributeName = "fulfilled")
    public Boolean getFulfilled() {
        return _fulfilled;
    }

    public void setFulfilled(final Boolean _fulfilled) {
        this._fulfilled = _fulfilled;
    }
    @DynamoDBAttribute(attributeName = "hygieneRequestID")
    public Double getHygieneRequestID() {
        return _hygieneRequestID;
    }

    public void setHygieneRequestID(final Double _hygieneRequestID) {
        this._hygieneRequestID = _hygieneRequestID;
    }
    @DynamoDBAttribute(attributeName = "location")
    public String getLocation() {
        return _location;
    }

    public void setLocation(final String _location) {
        this._location = _location;
    }
    @DynamoDBAttribute(attributeName = "notes")
    public String getNotes() {
        return _notes;
    }

    public void setNotes(final String _notes) {
        this._notes = _notes;
    }
    @DynamoDBAttribute(attributeName = "timestamp")
    public Double getTimestamp() {
        return _timestamp;
    }

    public void setTimestamp(final Double _timestamp) {
        this._timestamp = _timestamp;
    }
    @DynamoDBAttribute(attributeName = "username")
    public String getUsername() {
        return _username;
    }

    public void setUsername(final String _username) {
        this._username = _username;
    }

}